@Api_HostAddress = http://localhost:5100
@token = token

###
POST {{Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "admin@test.pl",
  "password": "Admin1!"
}

###
POST {{Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@test.pl",
  "password": "Admin1!"
}

###
GET {{Api_HostAddress}}/api/decisions/
Authorization: Bearer {{token}}

###
GET {{Api_HostAddress}}/api/decisions/1
Authorization: Bearer {{token}}

###
POST {{Api_HostAddress}}/api/decisions/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "New Decision",
  "description": "Description of the new decision",
  "expectedOutcome" : "To achieve this decision",
  "expectedReflectionDate" : "2026-12-31T18:00:00Z"
}

###
PUT {{Api_HostAddress}}/api/decisions/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 2,
  "title": "New Decision user",
  "description": "Description of the new decision",
  "expectedOutcome": "To achieve this decision",
  "visibility": 0,
  "actualOutcome": "Done",
  "lessonsLearned": null,
  "privateNotes": null,
  "satisfaction": 4
}

###
POST {{Api_HostAddress}}/api/decisions/3/publish
Authorization: Bearer {{token}}

###
GET {{Api_HostAddress}}/api/publicPosts?pageNumber=1&pageSize=5

###
POST {{Api_HostAddress}}/api/publicPosts/1/upvote