@Api_HostAddress = http://localhost:5100

###
GET {{Api_HostAddress}}/api/decisions/

###
GET {{Api_HostAddress}}/api/decisions/1

###
POST {{Api_HostAddress}}/api/decisions/
Content-Type: application/json

{
  "title": "New Decision",
  "description": "Description of the new decision"
}
